export const MAILER_USER = process.env.MAILER_USER
export const MAILER_PASSWORD = process.env.MAILER_PASSWORD
export const MAILER_SERVICE = process.env.MAILER_SERVICE
export const QUEUE_URL = process.env.QUEUE_URL
export const DATABASE_NAME = process.env.DATABASE_NAME
export const DATABASE_PORT = +process.env.DATABASE_PORT
export const DATABASE_PASSWORD = process.env.DATABASE_PASSWORD
export const DATABASE_HOST = process.env.DATABASE_HOST
export const DATABASE_USERNAME = process.env.DATABASE_USERNAME
export const CAR_SITE_FRONTEND_URL = process.env.CAR_SITE_FRONTEND_URL
export const NOTIFICATION_API_DOMAIN= process.env.NOTIFICATION_API_DOMAIN
export const NODE_ENV = process.env.NODE_ENV